[package]
name = "libdisplay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
include_bmp = { path = "include_bmp" }
konst = { version = "0.3", features = ["nightly_mut_refs"] }
